### ISSUE TITLE
use 'scan' command by default

### ISSUE THREAD

**Issue by sjourdan** [cloudskiff/driftctl#354] opened 2021-03-19 15:06 UTC
**Description**
`driftctl scan` is the basic and almost only command everybody uses.
Maybe we could use `scan` as a default command when `driftctl` is called?

**Example**

```bash
$ driftctl --from tfstate+s3://yaddi/yadda
[...]
```

**Comment by adamdonahue** [comment] 2021-03-22 17:03
I'm not sure I necessarily agree with this.  I think it's cleaner to specify `scan`, even though yes, it's one additional word.  It's also consistent with how a lot of other tools work.  There's no default action in `kubectl`, or `terraform`, etc.

**Comment by sundowndev** [comment] 2021-03-22 17:14
> I'm not sure I necessarily agree with this. I think it's cleaner to specify `scan`, even though yes, it's one additional word. It's also consistent with how a lot of other tools work. There's no default action in `kubectl`, or `terraform`, etc.

Just to clarify, the point of this is about having a short-cut for the scan command. The scan command will not be deleted anyway. So this shouldn't change much on the user experience. It's difficult to compare with the provided examples because kubectl and Terraform are two programs with a lot of features with a lot of commands. There's no way to tell what `terraform` without any argument would do; nor do kubectl. Driftctl was designed for one goal: scan the infrastructure for drifts. As we could say about curl: it was designed to simply request an HTTP endpoint; and curl run the request with no sub command. Hope it helps better understand this issue :-)

**Comment by adamdonahue** [comment] 2021-03-24 16:47
I understand your reasoning.  I think it's just interesting that scan is the default, which seems to break symmetry with other subcommands.  I'm trying to think of another subcommand-based option that has a default like that, which I'm sure there must be some.

If I run `driftctl` without options, will I get the help screen still?  I think that is better for usability.  

For example, if this is the default output now, not sure that's optimal:

```
(sre-driftctl-reporter) adonahue@devadmin:~/workspace/sre/management/infrastructure/groups/midas/infra$ driftctl scan
Terraform provider initialized (name=aws, alias=us-east-1)
Unable to scan resources: lstat terraform.tfstate: no such file or directory
```

Seems odd, especially if you're just seeing out for the first time (again, about usability).  I realize `-h` is the usual next step.  

Nevertheless, it's a compromise, as you said.   Just thought I'd provide some feedback as a devil's advocate.

**Comment by adamdonahue** [comment] 2021-03-24 16:47
I understand your reasoning. I think it's just interesting that scan is the default, which seems to break symmetry with other subcommands. I'm trying to think of another subcommand-based option that has a default like that, which I'm sure there must be some.

If I run driftctl without options, will I get the help screen still? I think that is better for usability.

For example, if this is the default output now, not sure that's optimal:

$ driftctl scan
Terraform provider initialized (name=aws, alias=us-east-1)
Unable to scan resources: lstat terraform.tfstate: no such file or directory
Seems odd, especially if you're just seeing out for the first time (again, about usability). I realize -h is the usual next step.

Nevertheless, it's a compromise, as you said. Just thought I'd provide some feedback as a devil's advocate.

**Comment by sundowndev** [comment] 2021-03-25 10:25
> Nevertheless, it's a compromise, as you said. Just thought I'd provide some feedback as a devil's advocate.

No problem! This seems to be a controversial issue for contributors as well so we're putting this in stand-by for now, since it's not on the v0.8 roadmap. Thanks again for sharing your feedback to us.

**Comment by sundowndev** [comment] 2021-06-23 08:26
I don't think this makes sense anymore since we've added the gen-driftignore command. Closing.

**Closed by sundowndev** 2021-06-23 08:26 UTC
Labels: kind/enhancement
