### ISSUE TITLE
Unable to "skip" / ignore a KMS key

### ISSUE THREAD

**Issue by leppikallio** [cloudskiff/driftctl#665] opened 2021-06-19 23:40 UTC
**Description**
Unable to "skip" a KMS key. The target account has (purposely) a KMS key which is owned by a different entity. The policy of the key is formed so that there is no access whatsoever to this key.
 
The problem seems to be how to get by this resource, how to exempt the resource so that the driftctl would bypass the resource.

```
ERRO[0027] AccessDeniedException: User: arn:aws:sts::<removed>:assumed-role/<role> is not authorized to perform: kms:GetKeyPolicy on resource: arn:aws:kms:eu-central-1:<removed>:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
        status code: 400, request id: 9fee23e9-a927-48da-976e-73c4b9d9bb58
Scanned resources (518)      
AccessDeniedException: User: arn:aws:sts::<removed>:assumed-role/<role> is not authorized to perform: kms:GetKeyPolicy on resource: arn:aws:kms:eu-central-1:<removed>:key/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx
        status code: 400, request id: 9fee23e9-a927-48da-976e-73c4b9d9bb58
```

I don't seem to figure out how to filter out / add .driftctl the CMK in this case?

Neither ARN nor the Key ID does seem to work.

**Environment**
 - OS: AWS Linux 2
 - driftctl version: v0.9.1
 - terraform version: v0.15.3
 - terraform providers versions: aws@3.37.0

**Comment by AzySir** [comment] 2021-06-20 20:52
+ 1 for this issue. I though this was specific to another line of code I was running that included boto3. However I have not debugged it yet.

**Comment by leppikallio** [comment] 2021-06-20 22:34
For some reason it almost looks like the problem might occur before the actual filtering. After various fancy filtering tests I ended up doing something which should exclude most oddities, like escaping the filter string etc.

KMS keys of course have KeyId instead of Id so this should exclude the troublemaker?
```
driftctl scan -f tfstate://terraform.tfstate --filter $'!(ends_with(KeyId, \'xxxxxxxxxxxxx\'))'
```
Still, just in case, testing this 
```
driftctl scan -f tfstate://terraform.tfstate --filter $'!(ends_with(Id, \'xxxxxxxxxxxxx\'))'
```
but unfortunately the result is still the same. 

In this case the key is indeed "out of reach" for a reason and the `kms:GetKeyPolicy` is going to fail. In such a case it might be good if the the scan would politely skip the resource but then report it at the end of the scan?

**Comment by sjourdan** [comment] 2021-06-21 07:54
hi! The pre-filtering behavior is linked to https://github.com/cloudskiff/driftctl/issues/456  (driftctl doesn't actually pre-filter requests, only post-processing for now, as of driftctl 0.9). This will change with 0.11

Also, to ignore a KMS key and its alias, here's what I add to my .driftignore: 

```
aws_kms_alias.alias/the-key-alias
aws_kms_key.e492d07f-0201-4346-a33b-727454d0787b
```

The ID is simply the key ID

Does it help?

**Comment by eliecharra** [comment] 2021-06-21 08:30
Filtering will not help you for this issue. The root cause here is an access denied exception not being mapped to a proper HTTP status code by AWS.

@AzySir already catched this kind of issue there : https://github.com/cloudskiff/driftctl/issues/640#issuecomment-860852150

I opened an issue to catch theses errors https://github.com/cloudskiff/driftctl/issues/666 and thus I'm closing this one as filtering happen after api call (for now) and will not help you as a workaround.

**Closed by eliecharra** 2021-06-21 08:30 UTC
Labels: kind/bug
